DEFAULT_PERMISSIONS = [
    {"_id": "users:read", "name": "View Users"},
    {"_id": "users:create", "name": "Create Users"},
    {"_id": "users:update", "name": "Edit Users"},
    {"_id": "users:delete", "name": "Delete Users"},
    {"_id": "roles:read", "name": "View Roles"},
    {"_id": "roles:create", "name": "Create Roles"},
    {"_id": "roles:update", "name": "Edit Roles"},
    {"_id": "roles:delete", "name": "Delete Roles"},
    {"_id": "roles:assign", "name": "Assign Roles"},
    {"_id": "permissions:read", "name": "Read Permissions"},
    {"_id": "tags:read", "name": "View Tags"},
    {"_id": "tags:create", "name": "Create Tags"},
    {"_id": "tags:update", "name": "Edit Tags"},
    {"_id": "tags:delete", "name": "Delete Tags"},
    {"_id": "projects:read", "name": "View Projects"},
    {"_id": "projects:create", "name": "Create Projects"},
    {"_id": "projects:update", "name": "Edit Projects"},
    {"_id": "projects:delete", "name": "Delete Projects"},
    {"_id": "projects:assign", "name": "Assign Members"},
    {"_id": "organizations:read", "name": "View Organizations"},
    {"_id": "organizations:create", "name": "Create Organizations"},
    {"_id": "organizations:update", "name": "Edit Organizations"},
    {"_id": "organizations:delete", "name": "Delete Organizations"},
    {"_id": "parties:read", "name": "View Parties"},
    {"_id": "parties:create", "name": "Create Parties"},
    {"_id": "parties:update", "name": "Edit Parties"},
    {"_id": "parties:delete", "name": "Delete Parties"},
    {"_id": "representatives:read", "name": "View Representatives"},
    {"_id": "representatives:create", "name": "Create Representatives"},
    {"_id": "representatives:update", "name": "Edit Representatives"},
    {"_id": "representatives:delete", "name": "Delete Representatives"},
    {"_id": "concerns:read", "name": "View Concerns"},
        {"_id": "concerns:create", "name": "Create Concerns"},
        {"_id": "concerns:update", "name": "Edit Concerns"},
    {"_id": "concerns:delete", "name": "Delete Concerns"},
    {"_id": "reports:view", "name": "View Reports"},
    {"_id": "reports:create", "name": "Create Reports"},
    {"_id": "settings:view", "name": "View Settings"},
    {"_id": "settings:edit", "name": "Edit Settings"},
    {"_id": "email_groups:read", "name": "View Email Groups"},
    {"_id": "email_groups:create", "name": "Create Email Groups"},
    {"_id": "email_groups:update", "name": "Edit Email Groups"},
    {"_id": "email_groups:delete", "name": "Delete Email Groups"},
    {"_id": "input_requests:read", "name": "View Input Requests"},
    {"_id": "input_requests:create", "name": "Create Input Requests"},
    {"_id": "input_requests:update", "name": "Edit Input Requests"},
    {"_id": "input_requests:respond", "name": "Respond to Input Requests"},
    {"_id": "input_requests:admin", "name": "Administer Input Requests"},
    {"_id": "performance:admin", "name": "Performance Admin"},
    {"_id": "performance:superadmin", "name": "Performance Superadmin"},
    {"_id": "users:lock", "name": "Lock Users"},
    {"_id": "users:unlock", "name": "Unlock Users"},
    {"_id": "dms.document.view", "name": "View DMS Documents"},
    {"_id": "dms.document.upload", "name": "Upload DMS Documents"},
    {"_id": "dms.document.edit_metadata", "name": "Edit DMS Document Metadata"},
    {"_id": "dms.document.delete", "name": "Delete DMS Documents"},
    {"_id": "dms.document.download", "name": "Download DMS Documents"},
    {"_id": "dms.document.bulk_download", "name": "Bulk Download DMS Documents"},
    {"_id": "dms.document.share", "name": "Share DMS Documents"},
    {"_id": "dms.document.link_reference", "name": "Link DMS Document References"},
    {"_id": "dms.status.update", "name": "Update DMS Status"},
    {"_id": "dms.comment.add", "name": "Add DMS Comments"},
    {"_id": "dms.dashboard.view", "name": "View DMS Dashboard"},
    {"_id": "dms.report.view", "name": "View DMS Reports"},
    {"_id": "dms.user.manage", "name": "Manage Client DMS Users"},
    {"_id": "dms.project.manage", "name": "Manage Client DMS Projects"},
    {"_id": "dms.audit.view", "name": "View DMS Audit Trail"},
    {"_id": "dms.claim.view", "name": "View Claims"},
    {"_id": "dms.claim.create", "name": "Create Claims"},
    {"_id": "dms.claim.edit", "name": "Edit Claims"},
    {"_id": "dms.claim.delete", "name": "Delete Claims"},
    {"_id": "dms.claim.manage", "name": "Manage Claims"},
    {"_id": "dms.claim.assess", "name": "Assess Claims"},
    {"_id": "dms.contract.appraisal.view", "name": "View Contract Appraisal"},
    {"_id": "dms.contract.appraisal.generate", "name": "Generate Contract Appraisal"},
    {"_id": "dms.contract.appraisal.edit", "name": "Edit Contract Appraisal"},
    {"_id": "dms.contract.appraisal.approve", "name": "Approve Contract Appraisal"},
    {"_id": "dms.contract.appraisal.reject", "name": "Reject Contract Appraisal"},
    {"_id": "dms.contract.appraisal.export", "name": "Export Contract Appraisal"},
    {"_id": "dms.contract.appraisal.create_registers", "name": "Create Contract Appraisal Registers"},
    {"_id": "dms.keydate.view", "name": "View Key Dates"},
    {"_id": "dms.keydate.create", "name": "Create Key Dates"},
    {"_id": "dms.keydate.edit", "name": "Edit Key Dates"},
    {"_id": "dms.keydate.delete", "name": "Delete Key Dates"},
    {"_id": "dms.keydate.manage", "name": "Manage Key Dates"},
    {"_id": "dms.keydate.export", "name": "Export Key Dates"},
    {"_id": "dms.keydate.eot_submit", "name": "Submit Key Date EOT"},
    {"_id": "dms.keydate.eot_approve", "name": "Approve Key Date EOT"},
    {"_id": "dms.keydate.baseline.freeze", "name": "Freeze Original Key Date Baseline"},
    {"_id": "dms.keydate.eot.lock_submission", "name": "Lock Key Date EOT Submission"},
    {"_id": "dms.keydate.eot.determine", "name": "Determine Key Date EOT"},
    {"_id": "dms.keydate.eot.freeze_determination", "name": "Freeze Key Date EOT Determination"},
    {"_id": "dms.keydate.achievement", "name": "Record Key Date Achievement"},
    {"_id": "dms.variation.view", "name": "View Variations"},
    {"_id": "dms.variation.create", "name": "Create Variations"},
    {"_id": "dms.variation.edit", "name": "Edit Variations"},
    {"_id": "dms.variation.delete", "name": "Delete Variations"},
    {"_id": "dms.variation.approve", "name": "Approve Variations"},
    {"_id": "dms.variation.export", "name": "Export Variations"},
    {"_id": "dms.bankguarantee.view", "name": "View Bank Guarantees"},
    {"_id": "dms.bankguarantee.create", "name": "Create Bank Guarantees"},
    {"_id": "dms.bankguarantee.edit", "name": "Edit Bank Guarantees"},
    {"_id": "dms.bankguarantee.delete", "name": "Delete Bank Guarantees"},
    {"_id": "dms.bankguarantee.extend", "name": "Extend Bank Guarantees"},
    {"_id": "dms.bankguarantee.release", "name": "Release Bank Guarantees"},
    {"_id": "dms.bankguarantee.export", "name": "Export Bank Guarantees"},
    {"_id": "dms.insurance.view", "name": "View Insurance Policies"},
    {"_id": "dms.insurance.create", "name": "Create Insurance Policies"},
    {"_id": "dms.insurance.edit", "name": "Edit Insurance Policies"},
    {"_id": "dms.insurance.delete", "name": "Delete Insurance Policies"},
    {"_id": "dms.insurance.export", "name": "Export Insurance Policies"},
    {"_id": "dms.insurance.manage_types", "name": "Manage Insurance Types"},
    {"_id": "dms.contract.master.view", "name": "View Contract Master"},
    {"_id": "dms.contract.master.manage", "name": "Manage Contract Master"},
    {"_id": "dms.contract.read", "name": "Read Contract Documents"},
    {"_id": "dms.contract.update", "name": "Update Contract Documents"},
    {"_id": "dms.contract.clause.create", "name": "Create Contract Clauses"},
    {"_id": "dms.contract.clause.read", "name": "Read Contract Clauses"},
    {"_id": "dms.ai.contract_processing.run", "name": "Run AI Contract Processing"},
    {"_id": "dms.ipc.view", "name": "View IPC Bills"},
    {"_id": "dms.ipc.create", "name": "Create IPC Bills"},
    {"_id": "dms.ipc.edit", "name": "Edit IPC Bills"},
    {"_id": "dms.ipc.delete", "name": "Delete IPC Bills"},
    {"_id": "dms.ipc.approve", "name": "Approve IPC Bills"},
    {"_id": "dms.ipc.export", "name": "Export IPC Bills"},
    {"_id": "dms.evidence_graph.view", "name": "View Evidence Graph"},
    {"_id": "dms.evidence_graph.verify", "name": "Verify Evidence Graph Links"},
    {"_id": "dms.evidence_graph.manage", "name": "Manage Evidence Graph"},
    {"_id": "dms.contract.timeline.view", "name": "View Contract Intelligence Timeline"},
    {"_id": "dms.chronology.view", "name": "View Chronology Builder"},
    {"_id": "dms.chronology.create", "name": "Create Chronologies"},
    {"_id": "dms.chronology.edit", "name": "Edit Chronologies"},
    {"_id": "dms.chronology.verify", "name": "Verify Chronology Events"},
    {"_id": "dms.chronology.export", "name": "Export Chronologies"},
    {"_id": "dms.chronology.admin", "name": "Administer Chronology Builder"},
    {"_id": "dms.arbitration.view", "name": "View Arbitration Drafts"},
    {"_id": "dms.arbitration.create", "name": "Create Arbitration Drafts"},
    {"_id": "dms.arbitration.edit", "name": "Edit Arbitration Drafts"},
    {"_id": "dms.arbitration.generate", "name": "Generate Arbitration Drafts"},
    {"_id": "dms.arbitration.export", "name": "Export Arbitration Drafts"},
    {"_id": "dms.arbitration.approve", "name": "Approve Arbitration Drafts"},
    {"_id": "dms.arbitration.audit", "name": "View Arbitration Draft Audit"},
    {"_id": "dms.arbitration.admin", "name": "Administer Arbitration Drafting"},
    {"_id": "dms.admin", "name": "Administer Client DMS"},
    {"_id": "drafting.request.view", "name": "View Drafting Requests"},
    {"_id": "drafting.request.create", "name": "Create Drafting Requests"},
    {"_id": "drafting.request.accept", "name": "Accept Drafting Requests"},
    {"_id": "drafting.request.assign", "name": "Assign Drafting Work"},
    {"_id": "drafting.draft.create", "name": "Create Expert Drafts"},
    {"_id": "drafting.draft.edit", "name": "Edit Expert Drafts"},
    {"_id": "drafting.draft.submit_for_review", "name": "Submit Drafts for Review"},
    {"_id": "drafting.review.perform", "name": "Perform Expert Review"},
    {"_id": "drafting.review.approve", "name": "Approve Expert Review"},
    {"_id": "drafting.review.return_for_revision", "name": "Return Draft for Revision"},
    {"_id": "drafting.final.view", "name": "View Final Drafting Output"},
    {"_id": "drafting.final.approve", "name": "Final Approval of Drafts"},
    {"_id": "drafting.audit.view", "name": "View Drafting Audit Trail"},
    {"_id": "drafting.workflow.state", "name": "View Drafting Workflow State"},
    {"_id": "drafting.workflow.resume", "name": "Resume Drafting Workflow"},
    {"_id": "drafting.workflow.cancel", "name": "Cancel Drafting Workflow"},
    {"_id": "drafting.workflow.checkpoints", "name": "View Drafting Workflow Checkpoints"},
    {"_id": "drafting.workflow.force_v2", "name": "Force Drafting Workflow v2 Fallback"},
    {"_id": "drafting.admin", "name": "Administer Drafting"},
    {"_id": "billing.plan.view", "name": "View Billing Plans"},
    {"_id": "billing.plan.manage", "name": "Manage Billing Plans"},
    {"_id": "subscription.entitlement.manage", "name": "Manage Subscription Entitlements"},
    {"_id": "subscription.usage.view", "name": "View Subscription Usage"},
    {"_id": "subscription.archive_access", "name": "Access Archive Subscription"},
    {"_id": "subscription.offboarding_export", "name": "Run Offboarding Export"},
]


def _display_name(permission_name: str) -> str:
    return permission_name.replace(".", " ").replace(":", " ").replace("_", " ").title()


def _append_missing_canonical_permissions() -> None:
    from ..core.permissions import CANONICAL_PERMISSIONS

    existing = {entry["_id"] for entry in DEFAULT_PERMISSIONS}
    for permission_name in CANONICAL_PERMISSIONS:
        if permission_name not in existing:
            DEFAULT_PERMISSIONS.append({"_id": permission_name, "name": _display_name(permission_name)})
            existing.add(permission_name)


_append_missing_canonical_permissions()
